# Generated by Django 4.1.5 on 2023-01-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogpic',
            name='modified',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='dogpic',
            name='original',
            field=models.ImageField(upload_to=''),
        ),
    ]
