# Generated by Django 4.1.5 on 2023-01-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_dogpic_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogpic',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
